# run with conda env update -f environment.yaml
name: laser-calculator
channels:
  - conda-forge
  - defaults
dependencies:
# use specific Python version to avoid possible incompatibilities
  - python=3.8
  - numpy=1.21
  - pint=0.17
  - ipython
  - uncertainties=3.1
  - sympy=1.8
  - cx_Freeze=6.9