name: laser-calculator
channels:
  - conda-forge
  - defaults
dependencies:
# use specific Python version to avoid possible incompatibilities
  - python=3.8
  - numpy
  - pint
  - ipython
  - uncertainties
  - sympy